### ISSUE TITLE
A problem when escaping backslash in a string

### ISSUE THREAD

**Issue by ehadx** [arzg/vim-swift#1]
When escaping backslash in a string, it thinks that I'm escaping the ending (") and treats the rest of the code as a part of the string.

<img width="843" alt="problem" src="https://user-images.githubusercontent.com/52679507/73884094-d1fee700-486d-11ea-98f3-b3f9b1231dfc.png">

**Comment by lunacookies** [comment]
Just a tip – looks like you aren’t using true colour (`set termguicolors`) in Vim. If you can, I would strongly recommend it, because I find it looks much nicer with :)
