### ISSUE TITLE
@statements aren’t highlighted

### ISSUE THREAD

**Issue by lunacookies** [arzg/vim-swift#2]
> Just another thing, statements starting with @ are not highlighted properly (**@IBAction**, **@objc** etc.). They should be purple as well, but they are cyan currently.

*Migrated from arzg/vim-colors-xcode#3.*

**Comment by lunacookies** [comment]
> statements starting with @ are not highlighted properly

Ah, ok. Is there a name for that kind of statement? And what characters are permitted in them?

**Comment by bitigchi** [comment]
They are called declaration attributes as far as I know...
Plus those, `#selector` should be also highlighted purple.
